FilePathCat="D:\\Sourrce\\Artifacts\\SourceCode\\_trunk\\CourseUI\\public\\images\\catagory\\"
FilePathCour="D:\\Sourrce\\Artifacts\\SourceCode\\_trunk\\CourseUI\\public\\images\\course\\"
FilePathVideo="D:\\Sourrce\\Artifacts\\SourceCode\\_trunk\\CourseUI\\public\\class\\video\\"
FilePathPdf="D:\\Sourrce\\Artifacts\\SourceCode\\_trunk\\CourseUI\\public\\class\\pdf\\"
ServicePort="1324"